### ISSUE TITLE
Improve runtime API

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1071]
Here is how to set up a runtime Graphback API:

```ts
const graphbackConfig = await getGraphbackConfig();

const schemaText = loadSchema(graphbackConfig.model);

const pubSub = new PubSub();

const runtimeEngine = new GraphbackRuntime(schemaText, graphbackConfig);
const models = runtimeEngine.getDataSourceModels();
const services = createKnexPGCRUDRuntimeServices(models, buildSchema(schemaText), db, pubSub);
const runtime = runtimeEngine.buildRuntime(services);

const apolloServer = new ApolloServer({
    typeDefs: printSchema(runtime.schema),
    resolvers: runtime.resolvers,
})
```

This is extremely convoluted and needlessly difficult to configure - nobody will want to use this. Much of this can be moved into our library, it could be as simple as this:

```ts
import { graphback } from 'graphback';

const pubSub = new PubSub();

const { typeDefs, resolvers, models } = graphback(pubSub);

const db = Knex(...);

const services = createKnexPGCRUDRuntimeServices(models, typeDefs, db, pubSub);

const apolloServer = new ApolloServer({
    typeDefs,
    resolvers,
    context: context => {
        ...context,
        models
    }
})
```

**Comment by lastmjs** [comment]
I absolutely agree with the complexity here. I'm just trying to setup the runtime now, and it is quite confusing, and I'm looking at multiple pieces of documentation and examples that seem to say slightly different things. I think the API could even be simplified beyond what you have suggested @craicoverflow. Couldn't the Knex db initialization be abstracted away? Why not provide the db details in the `.graphqlrc.yml`? We could provide an API that allows people to replace this db if they want to, but not require them to configure it by default. My dream for this project (I am coming from Prisma and had hoped they would do this, but they aren't going to) is to be able to write a simple data model schema in GraphQL SDL, import maybe one thing, pass it in, and have it work. To really be able to persuade others, this needs to be dead simple to start with so that it is obvious how much better a GraphQL-centered backend is than the status quo.

Great job so far! I'm very optimistic about the project.

**Comment by darahayes** [comment]
@craicoverflow I wonder how would database migrations fit into this? Is it something that the user looks after at an application level?

I've got a very rough prototype based on the API shown above. Going to post a draft PR for it soon to get your thoughts on it.

**Comment by craicoverflow** [comment]
Related https://github.com/aerogear/graphback/issues/1283

**Comment by wtrocki** [comment]
There are couple related issues that can be solved by refactor:

https://github.com/aerogear/graphback/issues/1157
https://github.com/aerogear/graphback/issues/1283
https://github.com/aerogear/graphback/issues/1157
https://github.com/aerogear/graphback/issues/1158
https://github.com/aerogear/graphback/issues/1283

I have done investigation on how our API could look like with possible variations. Let's have a call sometime this week to grab some feedback and document the desired outcome as part of this issue (while checking if that is going to address all related issues.
