### ISSUE TITLE
 GraphQL to MongoDB migrations

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1087]
It would nice if we could have some migration capabilities mapping a GraphQL schema to a Mongo database (using annotations to customisation migration).

There may already be a library out there so this is to research/investigate.

Things needed:

- Indexes
- Auto-incrementing IDs
- ...

**Comment by wtrocki** [comment]
Indexes can be passed quite easily on the data layer initialisation `ensureIndex`
For migration, we can recommend:
https://github.com/awapps/mongration

**Comment by wtrocki** [comment]
Dropped investigation as we going to explore options for migrations etc.

CC @ssd71

**Comment by ssd71** [comment]
> Indexes can be passed quite easily on the data layer initialisation ensureIndex

Agreed, sounds good

> Auto-incrementing IDs

I am not sure autoincrementing primary keys is a good idea in hindsight, as we are using primary keys to both delete and update, wdyt? Other than that, +1 for autoincrementing fields. MongoDB does not have that built-in, In mongoose, it can be achieved by [this](https://stackoverflow.com/questions/28357965/mongoose-auto-increment) workaround, although since we do not use hooks etc, some other kind of workaround is required here, I will see what I can dig up. 

I found [this](https://www.npmjs.com/package/mongoat) but like it was last updated 4 years ago not sure it is maintained anymore. I believe it's like mongo driver except with some features like hooks and createdAt, updatedAt(although I believe offix mongo does the latter already). We could always cook up a solution of our own (is that a weird thing to say?)

I will need to do some more research on `graphql-migrations` to see what other annotation features we could add

Let me know what you guys think :)

**Comment by wtrocki** [comment]
> Auto-incrementing IDs

Let's not chat about it in public ;) Mongo do not need that - it has hash generated id.
