### ISSUE TITLE
Rename default resolvers.ts file in generation template 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1174]
We need to rename resolvers.ts as for newcomers it might be confusing and mean that this is the only file that will contain resolvers. Additionally, we might create an empty custom resolvers file to show people how to provide their own

**Comment by machi1990** [comment]
As for the name, I am proposing `graphback-generated-resolvers.[jt]s`, a bit long but explicit. 

>  Additionally, we might create an empty custom resolvers file to show people how to provide their own

Agree, I'll do it on separate PR for reasons below. 

I am leaning toward adding the mechanism into `ResolverGeneratorPlugin` but would need your thoughts on that. 

As for the name, maybe `custom-resolvers.[jt]s` would suffice, could also be configurable (and opt in maybe). Quick question what happens when the file already exists? I'd say let's not override it.

**Comment by wtrocki** [comment]
CC @craicoverflow

**Comment by wtrocki** [comment]
How about
`graphbackResolvers.[jt]s` - implies generated

**Comment by machi1990** [comment]
> CC @craicoverflow
> 
> > Agree, I'll do it on separate PR for reasons below.
> 
> Sorry for not being clear. I was just to add that to the templates. There is no need to generate an empty file in plugin itself.

Nice. Thanks for clarification.

**Comment by machi1990** [comment]
> How about
> `graphbackResolvers.[jt]s` - implies generated

Great let's go with that. 

PS: Just noticed that we go with `camelCase` naming :)

**Comment by wtrocki** [comment]
Yep but that is up to the template developers.

**Comment by craicoverflow** [comment]
I am all on board with this change, thanks for doing it. I was thinking about it recently because if someone wants to add a new plugin on top of the resolver plugin in the future, they would have 2 resolvers files so distinctly naming this is less confusing.

**Comment by machi1990** [comment]
Thanks for the feedback @craicoverflow also saw your comment on the specific commit. Should be fixed by https://github.com/aerogear/graphback/pull/1194
