### ISSUE TITLE
Requiring _id field for mongo instead of `id`

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1547]
`Graphback was unable to create the specified indexes: E11000 duplicate key error collection: showcase.comment index: id_1 dup key: { : null }. If all else fails, try recreating the index manually.
`

Schema:

```graphql
"""
@model
@datasync
"""
type Task {
  """@id"""
  id: ObjectID!
}
```

Can be replicated in datasync starter.

**Comment by wtrocki** [comment]
CC @ssd71 

It is kinda critical issue as it is not possible to issue any query on this:

```
 "message": "E11000 duplicate key error collection: showcase.task index: id_1 dup key: { : null }",
```

**Comment by ssd71** [comment]
Looked around a bit, maybe it couldn't create index because there were multiple `id: null` documents in the collection?

I will have to take closer look if that's not it

**Comment by ssd71** [comment]
Either way, I think graphback should handle this error a bit better

**Comment by wtrocki** [comment]
That is what I have in db. Basically it fails after creating single document

<img width="557" alt="Screenshot 2020-06-24 at 17 33 48" src="https://user-images.githubusercontent.com/981838/85595606-ec7d0580-b640-11ea-871a-425e179161b1.png">

**Comment by ssd71** [comment]
So I replicated this and I think I am onto something here:

- The error in insert occurs because the document that is inserted has no id field, effectively treated as `id: null`, As an existing document also does not have an id field (hence `id: null`) the insertion fails as `@id` creates a unique index
- I am sure you already know this, but the `id` field in the GraphQL SDL is being mapped to `_id` for everything from inserts to deletes, but the index is being created on the `id` field, so the thing is even if we have a custom primary key, in the current state of Graphback Mongo support, the name of custom primary key *has* to be other than `id`
- At the heart of the problem it is a limitation of MongoDB Data Provider, and the way we are handling custom primary keys for MongoDB, I am thinking of some ways to go around this, a quick and dirty way (haven't read up enough to recommend) is to map the custom primary key field to `_id` in the graphback data layer for mongo and stop creating indexes on `@id` as there is already an index on `_id`, This is entirely possible because `_id` can support quite literally any BSON type with the exception of arrays <sup>[1](https://docs.mongodb.com/manual/core/document/#the-id-field)</sup>, I need to look a bit into how this is handled in Postgres to ensure consistency though, I would love some feedback on this from @craicoverflow and @machi1990 as well, if possibe, internally(I think) this would function exactly like how `id` is mapped to `_id` in MongoDBDataProvider

I hope you don't mind me saying this but, the `_id` field always has an index in MongoDB, so I don't think we need to put `@id` on `id` in the schema as schema's `id` maps to `_id` in the database fields, unless you have another point to put forward in which case, I will retract this hehe

**Comment by craicoverflow** [comment]
> At the heart of the problem it is a limitation of MongoDB Data Provider, and the way we are handling custom primary keys for MongoDB

To add to this, we are causing problems for ourselves by allowing any field to be assigned an ID and then mapping that to _id in the data provider. We have discussed doing this before but I think we should really require `_id: ID/ObjectID` instead of `id: ID` when using Mongo.

> and stop creating indexes on @id as there is already an index on _id

Yes, I don't see a need for `@id` in Mongo either. How will it work when someone assigns `email: String` as ID - will this be converted to an ObjectID in the document and its original content lost?

Should `@id` annotations be ignored in Mongo? We could print an info/warning message to the console.

**Comment by ssd71** [comment]
> > At the heart of the problem it is a limitation 
> Yes, I don't see a need for `@id` in Mongo either. How will it work when someone assigns `email: String` as ID - will this be converted to an ObjectID in the document and its original content lost?

This is an actual option, we can indeed use strings in the _id field instead of ObjectID, please see here: https://docs.mongodb.com/manual/core/document/#the-id-field
 _id can take anything except arrays

**Comment by wtrocki** [comment]
> To add to this, we are causing problems for ourselves by allowing any field to be assigned an ID and then mapping that to _id in the data provider. We have discussed doing this before but I think we should really require _id: ID/ObjectID instead of id: ID when using Mongo.

This!

**Comment by wtrocki** [comment]
> Yes, I don't see a need for @id in Mongo either. How will it work when someone assigns email: String as ID - will this be converted to an ObjectID in the document and its original content lost?

Worth to mention that in Mongo _id is sacret and very very rarely you do use any other ID. Thus entire id feature for Mongo seems corner case. If we force _id which will actually simplify a lot then we can also go further and try to recommend id for Postgres. Obviously, we will allow some deviation from it but core use case will be there.

**Comment by machi1990** [comment]
Hi @ssd71 @wtrocki I feel like #1565 right?

**Comment by ssd71** [comment]
This issue has become more about requiring `_id` field for mongo instead of `id` but maybe let's create separate issue for this? wdyt @wtrocki

**Comment by wtrocki** [comment]
hmm.. I think lets keep thus issue. There is good discussion and we need this stuff

**Comment by machi1990** [comment]
> This issue has become more about requiring `_id` field for mongo instead of `id` but maybe let's create separate issue for this? wdyt @wtrocki

> hmm.. I think lets keep thus issue. There is good discussion and we need this stuff

I've renamed the issue to `Requiring _id field for Mongo instead of id` following the above two comments. 

Is this related to https://github.com/aerogear/graphback/issues/1626?

**Comment by wtrocki** [comment]
Yes it is related

**Comment by machi1990** [comment]
This bug kind of relied on https://github.com/aerogear/graphback/pull/1749 which has now been merged. 

I feel like we can revive this "id" issue for MongoDB so that we close other related issues too.

**Comment by craicoverflow** [comment]
Do you see this working for both ObjectID and GraphbackObjectID or should it be restricted to GraphbackObjectID?

I believe there is different behaviour between both of these now.

**Comment by machi1990** [comment]
> Do you see this working for both ObjectID and GraphbackObjectID or should it be restricted to GraphbackObjectID?
> 
> I believe there is different behaviour between both of these now.

I see it being restricted to `_id: GraphbackObjectID`

**Comment by wtrocki** [comment]
Yes.. That will be the best and it is really going to help us to simplify implementation in the datastore.
