### ISSUE TITLE
[DataSync] Do we need createdAt field for datasync?

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1590]
Was just wondering if we need 'createdAt' for datasync? I am kinda leaning towards making it optional for datasync
This argument could be extended to creating some functionality for `@versioned` as well, where we could specify which fields we want, for example: `@versioned(updatedAt: false)` for someone who only wants the creation timestamp

**Comment by wtrocki** [comment]
It can be confusion. DataSync offers delta synchronization and conflict resolution. Default strategy for conflict resolution relies on lastUpdated.

I think we both know that this ended up little bit convoluted, but I will need to think of we need:

- deltasync
- conflict 

And how to represent those two separately. 
I wanted to keep them together to minimize amount of DataProviders we will need. I think you are right and we do not need it but we need to get some thoughts to avoid yet another deltadatasync. I think we need to avoid confusion for end users and also match some internal simplicity when maintaining data providers.

I think we need to push another strategy and then decide on what we will do here

**Comment by wtrocki** [comment]
I think we can sacrifice flexibility towards simplicity, but the challenge I have is that there are two ways to set this up: Conflicts are setup in code and versioning thing is set in schema. 
Pulling strategies into schema makes less sense because you might want to have custom one anyway. 
As I said it is easy to operate on the existing API once we bring the second strategy, but it looks like we going to have convoluted API so better to react quickly. 

Let's dedicate some time next week to chat about this.

**Comment by ssd71** [comment]
Hmm I completely agree, in hindsight the resulting API does seem rather convoluted but like you said let's bring in the strategy first maybe it will be better for us to look at it in entirety and then decide on improvements rather than ruminating before the fact hehe

**Comment by wtrocki** [comment]
I think if you work on strategy and conflict on separate branch without merging we will get 100 of the capacity we need and from there we going to work on improving this

**Comment by ssd71** [comment]
This is outdated now because we have specific `_lastUpdatedAt` field for DataSync that's different from the one used with `@versioned`, added in #1771 

Closing
