### ISSUE TITLE
consider `column.drop` as non safe ops and filter it out in `removeNonSafeOperationsFilter` 

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1673]
Noticed that the `` https://github.com/aerogear/graphback/blob/master/packages/graphql-migrations/src/plugin/MigrateOperationFilter.ts#L17 is missing the `column.drop`. We should consider adding it as the operation can be non safe.

/cc @wtrocki @craicoverflow

**Comment by craicoverflow** [comment]
It makes sense to me, I do remember there being a discussion about why `column.drop` should not be in this, but this was more our own usage purposes, not necessarily what the community wants or needs.

Either way, should `removeNonSafeOperationsFilter` become a function, so that the user can configure what is safe and what is not? Within a range of operations defined, including `column.drop`. Obviously we can't include all operations as many could prevent the database from being created.

**Comment by wtrocki** [comment]
This is definietly a bug and there was no reason why we not included this operation
