### ISSUE TITLE
Multiple providers for datasync

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1764]
Keeping in mind the discussion on #1755 
I would love to talk about how we should separate the different providers. Following the above linked discussion, I understand that:
- We would like a provider that conflicts on `_version` by default
- We would like for it to support different custom `procedures` for conflict detection and resolution
- Conflict resolution using delta table should be one of the above 'procedures` ONLY, meaning that if this specific procedure is not chosen, delta tables will not be created
- Leave what's on master as is

**Comment by wtrocki** [comment]
We should create separate issue to talk about end user API for DataSync. generic graphback one cannot be used due to invariant in operators:

If I pass version to datasource but not to plugin things will go bad etc.

That is why we need simple wrapper function that will create this backend but ensure that someone can pass state provider for detection and handling and strategies per operation type etc. 
Let's create separate issue

**Comment by wtrocki** [comment]
So instead of passing version we can have two helper functions that wrap current arguments but allows us to override providers

**Comment by machi1990** [comment]
@ssd71 @wtrocki will this be addressed by #1833 ?

**Comment by wtrocki** [comment]
Yep. This was purely discussion issue
