### ISSUE TITLE
MongoDB create method should ignore client side provided _id

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1900]
Regression. Both datasync and schema plugins add _id to create. 
This is not only invalid but causes clientSide id to break server:

```
message: "Variable "$input" got invalid value "storeclient.6f0bee74-25b0-48b4-a471-96bb9e15843a" at "input._id"; Expected type "GraphbackObjectID". Value is not a valid mongodb object id of form: storeclient.6f0bee74-25b0-48b4-a471-96bb9e15843a
```

Model seems invalid as well:
```
type Todo {
  _id: GraphbackObjectID!
  title: String
  description: String
  completed: Boolean
  _lastUpdatedAt: GraphbackTimestamp
}

input CreateTodoInput {
  ## This should be gone!
  _id: GraphbackObjectID
  title: String
  description: String
  completed: Boolean
}
```

**Comment by machi1990** [comment]
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment]
CC @ssd71

**Comment by machi1990** [comment]
I think it makes sense to ignore surrogate primary keys (`id: ID!` or `_id: GraphbackObjectID` in case of MongoDB) since these will be generated. 

The challenge is being able to reliably tell the underlying database. Is it MongoDB or a relational database (PostgreSQL) in our case. 

- We can make a better judgement that no one uses `ObjectID` as primary key in PostgreSQL as it does not make sense. With this assumption we can safely ignore `id: ID!` or `_id: GraphbackObjectID` from the generated input.
- Or in the longer term, introduce a means to query graphback core for the registered features (database) e.g when the knex package is loaded it automatically register a `knex` feature, likewise for the mongodb package a `mongodb`. Based on this information, plugins can reliably query them and make reasonable assumptions.

**Comment by machi1990** [comment]
> I think for me it will be only to not add `_id: GraphbackObjectID` as by definition we know about scalar type in the schema plugin.

Yes, but we'll want to do it only for MongoDB database.  I am wondering how do we get to do it properly without breaking things for one database (I am thinking of Postgres) as we probably would not want to ignore it. 

Also (whatever solution we'll go with), I think it makes sense to do it also for `id` since it be automatically generated.

**Comment by wtrocki** [comment]
Let's leave this then. I think that making quick fixes here might lead to issues. 
I see that _id is now ignored (wasn't before) for datasync so all good.

**Comment by machi1990** [comment]
Sure, we can revisit it later.

**Comment by wtrocki** [comment]
I would really like to have the ability to skip _id.
Number of the hacks I need to do in the client for this is to big. I will check if I can hack this (detect scalar and not include it for create)

**Comment by wtrocki** [comment]
Let's chat about this tommorow.

**Comment by machi1990** [comment]
> I would really like to have the ability to skip _id.

This makes sense. 

> Number of the hacks I need to do in the client for this is to big. I will check if I can hack this (detect scalar and not include it for create)

This is the simplest enough "hack", but I also think the client should not send the "_id" or "id" key during create. 

> Let's chat about this tommorow.

Sure :-)

**Comment by craicoverflow** [comment]
This is one month old - should it be left open?

**Comment by wtrocki** [comment]
It is huge problem. Just no time to fix it :)
