### ISSUE TITLE
Add Global conflict config for datasync

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1902]
Following up from https://github.com/aerogear/graphback/pull/1901#discussion_r472998891

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by machi1990** [comment]
@ssd71 regarding your https://github.com/aerogear/graphback/pull/1901#discussion_r473025919 

If you look at:

https://github.com/aerogear/graphback/blob/2dd562b703fbb279b06551bb30c055cccdae6864/packages/graphql-serve/src/runtime.ts#L42-L46

We are applying the same configuration for all the datasync models, so what I was hoping to see instead of this is just to supply a global configuration which will be applied to all the datasync models. 

Additionally, if a model has its own configuration supplied:
- We'll not ignore the global config and use this custom config if all options are there
- For missing options, use global configuration as default. 

The global config could be optional too, meaning we can provide recommended defaults values i.e if user has not supplied it, we'll define one with sensible defaults.   

PS: All of this is open to discussion / counter proposal.
