### ISSUE TITLE
offer a plain fastify template 

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#2065]
**Is your feature request related to a problem? Please describe.**

There is no fastify template, we can add two:
- mongo based one
- postgres based one

**Describe the solution you'd like**

You can checkout https://github.com/aerogear/graphback/blob/99bb8102cf95482fd70efeddba772c2019ae8391/performance/benchmarks/graphback-fastify.js#L1-L27 
 
on how to setup the Graphback with [fastify-gql](https://github.com/mcollina/fastify-gql)

And 
- https://github.com/aerogear/graphback/tree/99bb8102cf95482fd70efeddba772c2019ae8391/templates/ts-apollo-mongodb-backend
- https://github.com/aerogear/graphback/tree/99bb8102cf95482fd70efeddba772c2019ae8391/templates/ts-apollo-postgres-backend

on how to setup a graphback template. As for the naming, `ts-fastify-gql-postgres-backed`, `ts-fastify-mongo-backed` will be good for consistency, but anything else will do. 

Once that is done, we'll need to update:
https://github.com/aerogear/graphback/blob/99bb8102cf95482fd70efeddba772c2019ae8391/packages/create-graphback/src/init/starterTemplates.ts#L13-L71 

to include the added templates.

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment]
I have tried to do it in graphback first. It feels like there is will be sooo many templates with repeating stuff. All our templates are express.js without mentioning it. I'm questioning if we really need express at this point (having proper justification and link to screenshot in the readme can work here really well and it will make all our templates production ready. 

@craicoverflow @machi1990 WDYT? I have tried it and there seems to be no impact on the current code.

**Comment by wtrocki** [comment]
Actually I have found critical bug when doing this. Our subscriptions seem to be working only with Apollo (using graphql-express, and subscriptions have different format).
Since just this morning recent announcement of the new library that fixes all the issues in subscriptions it makes sense to change all of this stuff. It will not be breaking peoples code so it can be post 1.0 no problem

**Comment by machi1990** [comment]
> It feels like there is will be sooo many templates with repeating stuff. 

I think it's fine as long as they are offering different flavours of dbs or http servers

> It will not be breaking peoples code so it can be post 1.0 no problem

Cool.

**Comment by RinkiyaKeDad** [comment]
Hi @machi1990 I would like to work on this. Could you please answer a few question I have regarding this?
1. What does the code in ```graphback/performance/benchmarks/graphback-fastify.js``` do? As far as I know graphback doesn't have a fastify template so how does this file relate graphback and fastify.
2. In order to begin creating the template should I just follow this structure of https://github.com/aerogear/graphback/tree/99bb8102cf95482fd70efeddba772c2019ae8391/templates/ts-apollo-mongodb-backend ?
What I want to ask is that doesn't this contain the **generated** template, implying I should write the code for generation of this template somewhere else? Or does this work by writing the template itself? If yes then how will it update automatically to someone's changes to their model?

**Comment by wtrocki** [comment]
We have performance tests that use template but we do not have template that uses it. 
So this is equivalent to saying that we can do things really fast but only if we have X ( and this X means fastify template. 

From my personalized point of view I would prefer to migrate current templates out of express as express itself have been struggling with merges and community and overal is very stagnant. We also have strong ties to fastify. 


Overal stack we can use is:

- Fastify
- GraphQL Tools (not apollo)
- Apollo-Express (reference specification)

**Comment by wtrocki** [comment]
To answer second question - you can change and rename apollo templates to fastify. It will be much better/easier instead of creating new ones.

**Comment by RinkiyaKeDad** [comment]
Thanks for answering my queries @wtrocki.

> To answer second question - you can change and rename apollo templates to fastify. It will be much better/easier instead of creating new ones.

I'm a bit confused about as to where I should begin writing my code. Should I be changing the files in the respective folders, that is, graphback/templates/ts-apollo-mongodb-backend/ or should I be editing the files responsible for the generation of templates which I think are located at, packages/graphback-codegen-client/src/templates/gqlTemplates.ts?

**Comment by wtrocki** [comment]
Fastify is server side Node.js technology. 
packages/graphback-codegen-client/src/templates/gqlTemplates.ts - is responsible for generating client side graphql queries. 

> you can change and rename apollo templates to fastify.

graphback/templates/ts-apollo-mongodb-backend/ => graphback/templates/ts-fastify-mongodb-backend/

After rename you can use fastify inside rather than than apollo-express.
Happy to explain it further. PS: Readme.md has link to our community chat if you would require assitance/immediate help or guidance.

**Comment by machi1990** [comment]
Closed by #2153 thanks to @RinkiyaKeDad for the awesome contribution.
