### ISSUE TITLE
Create graphback db command

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#47]
## About
`graphback db` will create Postgres database with tables and relations from the model

**Comment by ankitjena** [comment]
@wtrocki your views?

**Comment by wtrocki** [comment]
in my opinion we should first ask if someone wants to have just DDL files or major changes directly on the database. secondly we should not support dropping or removing the data only additions should be added for obvious reasons. the major problem is how to maintain this data base connection. we can say that for production we recommend DDL statements and direct db generation for local development

**Comment by wtrocki** [comment]
having hard dependency to postgress is not desired. I think we first need to implement cli config and then do this task

**Comment by ankitjena** [comment]
> in my opinion we should first ask if someone wants to have just DDL files or major changes directly on the database. secondly we should not support dropping or removing the data only additions should be added for obvious reasons. the major problem is how to maintain this data base connection. we can say that for production we recommend DDL statements and direct db generation for local development

Since production might always be at later stages than development, we can do both and store the DDL statements in a file?

**Comment by wtrocki** [comment]
How this is going to work?
Are we going to support only initial database creation? How about cases when building new app for existing database?

**Comment by ankitjena** [comment]
We could create a database with the name of the project, that way it won't affect existing database in case of building new app. 
But a thing to care for is if a user edits his model, then table creation will be skipped if it's already been created or deletes a Type then the table would exist in the database

**Comment by wtrocki** [comment]
> We could create a database with the name of the project, that way it won't affect existing database in case of building new app.

You mean on localhost or some remote server?

> But a thing to care for is if a user edits the model, then table creation will be skipped if it's already been created or deletes a Type then the table would exist in the database

Hm.. this will render the entire feature not functional. If user edits model we need to update database simply because it will no be possible to query data. 

Let's talk about how this could work in general. Like I totally do not see it now. 

If we have diffs locally for the development database then those diffs will work only for this particular database, which can be in the diferent state than any other database. We cannot avoid diffing the current dataset and applying changes. 

Because probably pointing tool to any other database than local one is not that realistic scenario we can assume that people will have tags for their work so then they can use local db state (actually the previous state to calculate diff changes)

**Comment by ankitjena** [comment]
Closing this
