### ISSUE TITLE
OneToMany directive not working as expected

### ISSUE THREAD

**Issue by jcbdev** [aerogear/graphback#536]
I think ```@OneToMany()``` just is not working currently.

if i try ```graphback generate``` with the following gql:

```
type Person {
  id: ID!
  name: String!
}

type Ticket {
  id: ID!
  code: String!
  holder: Person! @OneToMany(field: "tickets")
}
```

I get the following generated schema without an array of tickets?
```
  type Person {
    id: ID!
    name: String!
    ticket: Ticket!
  }

  type Ticket {
    id: ID!
    code: String!
    holder: Person
  }
```

I would have expected the following to be generated for Person:
```
  type Person {
    id: ID!
    name: String!
    tickets: [Ticket!]
  }
```

**Comment by wtrocki** [comment]
Hi

We are in the process of refining OneToMany directive.
May I ask if you using graphback runtime or graphql-cli? 
We do not have relationship support for runtime yet. 

As for schema generation. I believe that `OneToMany` should be added on the opposite side as a workaround now. If we do that then the individual field will be generated - but I will expect this to be fixed in next release

**Comment by wtrocki** [comment]
@craicoverflow Would this case be fixed with the new generation engine

**Comment by craicoverflow** [comment]
Hey @jcbdev - you are using the directive on the wrong side of the relationship!

https://graphback.dev/docs/relationships#one-to-many

> @craicoverflow Would this case be fixed with the new generation engine

This case _will_ be fixed in the generation engine.

@jcbdev - we have implemented a new database migration engine recently. We made a decision to use [`graphql-annotations`](https://github.com/Akryum/graphql-annotations) for relationship tracking instead of directives. You can read why in https://github.com/aerogear/graphback/issues/539. This work is happening in https://github.com/aerogear/graphback/pull/562.

At the moment the migration engine does not automatically generate the field on the relation table. You have to explicitly add the fields you want to the input model.

**Comment by wtrocki** [comment]
@craicoverflow Thank you for response. Let's close this issue as we suggested fix.
We going to review it again when pushing new mechanism
