### ISSUE TITLE
[Discussion] Create relationship from either side

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#557]
https://github.com/aerogear/graphback/pull/538#discussion_r355585942

```gql
type User {
  id: ID!
  messages: [Message] # this does not create a relationship
}

type Message {
  id: ID!
  user: User # this does create a relationship
}
```

It should be possible to create a foreign key constraint from either side of this model. Currently only a N:1 or 1:1 will do this.

**Comment by craicoverflow** [comment]
Should we also generate fields on the generated schema? Let's take following example:

```gql
type User {
  id: ID!
  name: String
  messages: [Message] # this does not create a relationship
}

type Message {
  id: ID!
  text: String
}
```

I understand that we expect this to create a `userId` column in the `message` table. Should we also add the `Message.user` field to the generated schema?

I can see the benefit of this, but I also see this as a step that the user could do. If I want to execute the following query:

```gql
query {
  findAllMessages {
    id
    text
    user {
      id
      name
    }
  }
}
```

They could add `Message.user` to the data model as they know this is a field they would want to query.

What do you think @wtrocki?

**Comment by wtrocki** [comment]
> I understand that we expect this to create a userId column in the message table. Should we also add the Message.user field to the generated schema?

We were doing it before and we kinda removed it. Generally, we can:

1) Assume that users will always need to have bidirectional relationships in model and enforce it by validation

2) Generate that field automatically and use generated schema for migrations. 

3) Trying to map current state and produce unclear docs for it 

4) Force relationship annotations everywhere to have consistency.

--------------

Ad 1. I think that validation here might be a problem to end-users. 
There could be situations where business logic will dictate to not have this field. 
Additionally user experience, in this case, is not great. Having manual edit in model etc.

IMHO this option is strong no-no

Ad2. We had this discussion already. We can generate that field but only in target schema that is not available for the db migration now. 

Going to this approach will have a number of benefits for migration package - it will be just generic. Then we can use graphql-annotations outside to get the same data.. 

However this requires investigation to see how we can change graphback to require full schema instead of model. 

3) We are in this position now. We could actually drop it to people and get feedback but I think this will be really tricky pass the message. Def no go zone for me

4) This is tempting and I think that it do not exclude the nr 2.  or nr 1 (as a warning)
If we decide to just use annotation as marker and use some defaults then we can reliably use that in entire ecosystem. I would love to see that but I think we need investigation to see if there is no corner cases for this

**Comment by wtrocki** [comment]
@craicoverflow Feel free to reopen this issue if needed.
