### ISSUE TITLE
Files are duplicated when switching between JS and TS

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#704]
![Screenshot from 2020-02-11 15-30-07](https://user-images.githubusercontent.com/11743717/74251188-a81d4880-4ce3-11ea-982f-90af658fcaab.png)

Old files should be removed between generations as they will both have the same export name, causing runtime issues.

**Comment by wtrocki** [comment]
"Never remove files based on user input" ;) 
I trully think that if someone uses generator and swapping the values like filePath, outputPath they should clean up old files themselves. 
We cannot really cater people messing with config and try to remove stuff because we might happen to remove file that wasn't ours. 

TL;DR - when changing config values people need to manually remove old files.

**Comment by wtrocki** [comment]
Closing as outdated
