### ISSUE TITLE
Validate documentation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#811]
We mantainers know graphback and docs really well but for someone starting it
could be hard to get in. We looking for feedback and fixes for documentation
 Any info/change matters

**Comment by NomadXD** [comment]
@wtrocki I went through the docs couple of weeks ago and some parts are still confusing. How about we add a comments section at the bottom of the page so that readers will be able to ask questions right in the docs and make clarifications? It'll be easy for both them and us instead of going through explanations in discord. See the attached image. Thanks 
 
![Screenshot from 2020-03-01 14-45-41](https://user-images.githubusercontent.com/43727928/75623024-22970500-5bcc-11ea-9567-d5c2f41503b1.png)

**Comment by wtrocki** [comment]
Great idea. I would go with page extension in docusaurus rather than adding disqus to every page

**Comment by jaskeerat789** [comment]
The Problem I faced while trying to understand the project a couple of weeks ago was that it had good documentation for a developer already familiar with graphQL. Someone like me had a little difficulty in understanding some jargon though I had some experience in graphQL.

**Comment by jaskeerat789** [comment]
I also think that we should have a little more detailed doc for the contributors or someone trying to figure out how things work.

**Comment by wtrocki** [comment]
Outlook:

- Add information about general graphql 
- Improve CONTRIBUTING.md file

**Comment by wtrocki** [comment]
Validation done
