### ISSUE TITLE
Roadmap for Graphback 1.0-Beta

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#978]
## Graphback Roadmap

Work in progress.

For individual issues see:
https://github.com/aerogear/graphback/milestone/3

**Comment by craicoverflow** [comment]
Here are some of my findings so far:

## Model

1. Missing a `@CreatedAt` and `@UpdatedAt` directive to set timestamp values from runtime datasources.
2. [MongoDB] `db.default` `db.unique` annotations do not do anything for MongoDB as there is no migrations. These seem like something we should have in place for MongoDB.

## API

3. `createKnexCRUDX` should be able to accept `Knex.Config` or `any` so that the template does not require Knex to be installed directly.
4. Should PubSub instance be optional when creating CRUD Services?

## CLI*

1. `graphback config` should not generate a blank data model if user selects no model - they probably have their own already.
2. General CLI experience improvements - minor.

## CRUD Spec

**XFields**

We need a separate input type for querying fields. For example `NoteFields` and `NoteInput`.

**Update Mutation**

The update mutation relies on the ID field to do the update. This presents two problems for the future:

- If a model does not have an ID field, the update cannot be performed
- The current approach is very limited and people would have to write their own custom update resolvers for scenarios other than updating by ID field.

Proposed spec change:

`updateNote(where: NoteFields, input: NoteInput)`

This change would allow the user to update multiple items by a matching criteria; For example if somebody wants to set all notes from `published: false` to `published: true` where created > 3 days ago.

This would make a much more useful standard Update resolver.

**Delete Mutation**

The exact same logic as **Update Mutation** can be applied to delete mutations.

```
`deleteNote(where: NoteFields)`
```

`fields` input variable should be changed to `filter` or `where`. Fields does not make sense for what it is used for.

**Comment by wtrocki** [comment]
@craicoverflow Amazing work! 
Closing as we going to create new one
